# Generated by Django 2.2.10 on 2020-03-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200316_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarks',
        ),
    ]
