# Generated by Django 2.2.10 on 2020-03-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200323_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategoris', to='blog.Kategori'),
        ),
    ]
