# Generated by Django 2.2.10 on 2020-03-26 07:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200326_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='atrikel',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
