# Generated by Django 3.0.4 on 2020-03-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='bookmarks',
            new_name='bookmark',
        ),
    ]
