# Generated by Django 3.0.4 on 2020-03-31 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0002_auto_20200331_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastdislike',
            name='users',
            field=models.ManyToManyField(related_name='requirement_podcast_dis_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcastlike',
            name='users',
            field=models.ManyToManyField(related_name='requirement_podcast_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
