# Generated by Django 2.2.10 on 2020-03-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='user/profile'),
        ),
    ]
