# Generated by Django 2.2.10 on 2020-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200312_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alamat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user/profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
