# Generated by Django 2.2.10 on 2020-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200312_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user/profile'),
        ),
    ]
